plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

def releaseVersion = System.getenv('GITHUB_TAG')?.replaceFirst(/^v/, '') ?: mod_version
def minecraftVersionLabel = minecraft_version_label

group = maven_group
version = "${releaseVersion}+${minecraftVersionLabel}"

base {
    archivesName = "${mod_id}-fabric"
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.toVersion(java_version)
    targetCompatibility = JavaVersion.toVersion(java_version)
}

sourceSets {
    main {
        java {
            srcDir 'common/src/main/java'
            srcDir 'fabric/src/main/java'
        }
        resources {
            srcDir 'common/src/main/resources'
            srcDir 'fabric/src/main/resources'
        }
    }
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }

    mavenCentral()

    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    implementation "maven.modrinth:geckolib:${geckolib_version}"

    compileOnly "org.jetbrains:annotations:26.0.2"

    implementation include("com.electronwill.night-config:core:${night_config_version}")
    implementation include("com.electronwill.night-config:toml:${night_config_version}")
}

tasks.named('processResources', ProcessResources).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    var replaceProperties = [
            minecraft_version            : minecraft_version,
            minecraft_version_label      : minecraft_version_label,
            minecraft_version_range      : minecraft_version_range,
            fabric_loader_version        : fabric_loader_version,
            fabric_loader_version_range  : fabric_loader_version_range,
            fabric_api_version           : fabric_api_version,
            fabric_api_version_range     : fabric_api_version_range,
            java_version                 : java_version,
            mod_id                       : mod_id,
            mod_name                     : mod_name,
            mod_version                  : project.version,
            mod_description              : mod_description,
            license                      : license,
            geckolib_version             : geckolib_version,
    ]

    inputs.properties replaceProperties

    filesMatching(['fabric.mod.json', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = java_version.toInteger()
}
