# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
maven_group=dev.xylonity.bonsai.ghosts
mod_id=ghosts
mod_name=Ghosts
mod_version=0.1.4
release_type=release
mod_description=A minecraft mod that adds friendly ghosts to your world!
license=GPL-3.0-only

# Minecraft
minecraft_version=26.1.2
minecraft_version_label=26.1.x
minecraft_version_range=~26.1
java_version=25

# Fabric
loom_version=1.16.2
fabric_loader_version=0.19.2
fabric_loader_version_range=>=0.19.2
fabric_api_version=0.149.0+26.1.2
fabric_api_version_range=>=0.144.3

# Dependencies
geckolib_version=5.5
night_config_version=3.8.3

# Publishing
modrinth_project_id=ghost
curseforge_project_id=1548313
