# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=ghosts
mod_name=Ghosts
mod_author=Joosh7889, Xylonity
mod_version=26.1.2-0.1.1-fabric
release_type=release
mod_description=A minecraft mod that adds friendly ghosts to your world!
license=GPL-3.0-only

# Fabric
minecraft_version=26.1.2
java_version=25
loom_version=1.16.2
fabric_api_version=0.149.0+26.1.2
fabric_loader_version=0.19.2

# Dependencies
geckolib_version=5.5.1
geckolib_curseforge_file_id=7913636
night_config_version=3.8.3

# Publishing
maven_group=dev.xylonity.bonsai.ghosts
modrinth_project_id=ghost
curseforge_project_id=602665
